### ISSUE TITLE
For a client using custom store, there should be an option to provide a path.

### ISSUE THREAD

**Issue by aakash10897** [polotno-project/polotno-node#10]
currently the create instance call only takes url. This url will always be the case where the client is hosted remotely. What if store is present in a common package used by the client as well as the backend. In that case an option to use a file path should also be there in createInstance call

**Comment by lavrton** [comment]
File path to what? To final html bundle? If so, you can use `url` for that.

```js
const url = `file:${path.join(__dirname, 'dist', 'index.html')}`;
```
