### ISSUE TITLE
Using cache for browser

### ISSUE THREAD

**Issue by aakash10897** [polotno-project/polotno-node#11]
Also puppeteer.launch() gives an option to se userDataDir. I guess it is related to caching. Can we include this in the code if this can help render faster ?

**Comment by lavrton** [comment]
What is your use case? Do you want to preserve cache over creating/closing many instances?

**Comment by aakash10897** [comment]
No just a single instance.

**Comment by aakash10897** [comment]
I looked indto this more and found out that this is useful when we want to share stuff across instances/sessions which is not valid for my usecase, so closing the issue.
