### ISSUE TITLE
Can CMYK images be exported?

### ISSUE THREAD

**Issue by glacierck** [polotno-project/polotno-node#2]
Can CMYK images be exported? This is the color used for printing. At the same time, I don't see the function of switching color space to CMYK in the demo. This is important for the custom printing industry. Are there any solutions?

**Comment by lavrton** [comment]
It should be possible, but it is not in the scope of the library. https://github.com/lovell/sharp should support such conversion. So steps are:

1. export design JSON into png or jpg with `polotno-node`
2. convert colorspace with `sharp` tool.  https://stackoverflow.com/a/64631984/512042, https://sharp.pixelplumbing.com/api-colour#tocolourspace
