### ISSUE TITLE
Chrome-Aws-Lambda Dependency Does not Support Node 16+/LTS 

### ISSUE THREAD

**Issue by alexluongfm** [polotno-project/polotno-node#3]
The Chrome AWS Lambda dependency is unmaintained and tied to node 14, see someone's [PR on that](https://github.com/alixaxel/chrome-aws-lambda/pull/274). 

Polotno-node latest doesn't work on Lambda with node-14, works with node 18, partially, except for shared library issues. This is tied to the outdated chrome aws lambda dependency. 

Is it possible to change the Chrome AWS Lambda package to something updated for Node 18/LTS usage? Someone's suggestion of [Sparticuz fork](https://github.com/Sparticuz/chrome-aws-lambda). Looks like the future updates has changed to https://github.com/Sparticuz/chromium

**Comment by lavrton** [comment]
Thanks for providing the links. Where did you try to host it? Amazon Lambda? Or something else?
