### ISSUE TITLE
Video support issue

### ISSUE THREAD

**Issue by jhonix22** [polotno-project/polotno-node#6]
Should be `polotno-node/video` instead. This got me scratching my head for a couple of minutes.
<img width="510" alt="image" src="https://github.com/polotno-project/polotno-node/assets/4106219/b5b314c6-4d65-43fa-985d-8d3b0d68982b">

**Comment by jhonix22** [comment]
Also, is video support currently working?
<img width="822" alt="image" src="https://github.com/polotno-project/polotno-node/assets/4106219/000fce51-7a51-457e-9c73-32dcc74ad1c1">
I noticed when I installed `polotno-node`, there are some errors like `axios` not installed when calling `jsonToVideo`. I've checked the `packge.json` file of polotno-node and I saw that it is in the `devDependencies` which will obviously not going to be installed on my end.
<img width="680" alt="image" src="https://github.com/polotno-project/polotno-node/assets/4106219/a6cf0208-c2a3-4ca5-b981-15dc1899dadc">

So my question is, can this be experiment now publicly or not yet?

**Comment by lavrton** [comment]
I updated the docs. Does it help?

**Comment by jhonix22** [comment]
> I updated the docs. Does it help?

Yep thanks. But how about my other question? can you verify that we should install the mentioned dependencies for now separately so to go through?

**Comment by lavrton** [comment]
Only what is mentioned in the docs. Later I will make a release differently, so you will not have to install them manually. But this is the way for now.
